### ISSUE TITLE
Colerar Internationalization

### ISSUE THREAD

**Issue by Colerar** [z-shell/community#10]
### Contact Details

233hbj@gmail.com

### Username

@colerar

### Property you are interested or would like to moderate.

Internationalization

### According to the selection above, please describe your role from your own point of view.

I will be working on localization and internationalization for `zh-CN` and `zh-TW`. In this way, I hope to help people who use these languages quickly become familiar with Z-Shell and its projects.

At the same time, we need to developed translation standards including global or language-specific rules. This allows us to maintain the quality of translations.

### Organization support

Provides the ability to deploy localized text.

Tecnical support for automatic conversion between language varieties. 

For Chinese, in the initial period of lack of contributors, different varietys (like zh-TW) can be converted automatically with only several errors. For example, [opencc project](https://github.com/BYVoid/OpenCC) focuses on "Conversion between Traditional and Simplified Chinese". Wikipedia also provides different varieties (actually a long list: zh-Hans, zh-Hant, zh-CN, zh-SG, zh-TW, zh-HK...), manually convert them all is difficult, though we do not need so many varieties.

## external links

[An article](https://www.w3.org/International/articles/language-tags/) to understand Language Tags and the difference between `zh-CN` and `zh-Hans`.

### Governance & Steering committee.

- [X] I am familiar with and agree with the governance & technical steering committee.

### Code of Conduct

- [X] I agree to sustain healthy interactions and will follow this project's Code of Conduct

**Comment by ss-o** [comment]
@Colerar let me know if need any support. I already prepared a few things for the topics you mentioned.
