### ISSUE TITLE
team: Join Borley for i18n

### ISSUE THREAD

**Issue by borley1211** [z-shell/community#11]
### Contact Details

borley1211@gmail.com

### Username

@borley1211

### Property you are interested or would like to moderate.

Documentation

### According to the selection above, please describe your role from your own point of view.

JP Translation of Documentation

### Governance & Steering committee.

- [X] I am familiar with and agree with the governance & technical steering committee.

### Code of Conduct

- [X] I agree to sustain healthy interactions and will follow this project's Code of Conduct

**Comment by ss-o** [comment]
Hey @borley1211,

No plans to start a project based on your interests? :see_no_evil:  :+1:

**Comment by borley1211** [comment]
Yeah, for the moment
