### ISSUE TITLE
team: i18n

### ISSUE THREAD

**Issue by 0xMRTT** [z-shell/community#31]
### Username

@0xMRTT

### Email

0xMRTT@tuta.io

### Assign @zshell.dev email forwarder

- [X] Assgin email

### Property you are interested or would like to moderate.

Internationalization

### According to the selection above, please describe your role from your point of view.

I will translate ZW in French 

### Organization support

I can answer in French, German and English

### Governance & Steering committee.

- [X] I am familiar with and agree with the governance & technical steering committee.

### Code of Conduct

- [x] I agree to sustain healthy interactions and will follow this project's Code of Conduct

**Comment by ss-o** [comment]
### @0xMRTT

- [ ] Verify
- [ ] Invite to @z-shell/i18n

**Comment by 0xMRTT** [comment]
I think that I can close the issue?

**Comment by pskarma** [comment]
First one? :dart:

**Comment by 0xMRTT** [comment]
What are DS1 and DP2 ?

**Comment by ss-o** [comment]
It's my check for users. It means your account has no history of being verified. I did it manually with your other accounts.

**Comment by 0xMRTT** [comment]
?
